[build]
builder = "nixpacks"
buildCommand = """
# Create directory structure
mkdir -p /app/src/api
cp -r api/src/* /app/src/api/

# Copy necessary files
cp README.md /app/
cp pyproject.toml /app/
cp setup.py /app/

# Install dependencies
python -m pip install --upgrade pip setuptools wheel
python -m pip install -e .[cpu]
"""

[deploy]
startCommand = "uvicorn api.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100

[env]
PYTHON_VERSION = "3.10"
USE_GPU = "false"
OUTPUT_DIR = "/tmp/output"
TEMP_FILE_DIR = "/tmp/kokoro_temp"
MODEL_DIR = "/app/src/api/models"
VOICES_DIR = "/app/src/api/voices/v1_0" 