[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn api.src.main:app --host 0.0.0.0 --port $PORT --log-level debug"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[phases.setup]
nixPkgs = ["python310", "gcc", "pkg-config"]
aptPkgs = ["python3-dev", "build-essential"]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip setuptools wheel",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "mkdir -p /app/api/src/models /app/api/src/voices/v1_0 /tmp/output /tmp/kokoro_temp"
]

[env]
PYTHON_VERSION = "3.10"
USE_GPU = "false"
OUTPUT_DIR = "/tmp/output"
TEMP_FILE_DIR = "/tmp/kokoro_temp"
MODEL_DIR = "/app/api/src/models"
VOICES_DIR = "/app/api/src/voices/v1_0"
PYTHONUNBUFFERED = "1"
PORT = "8000" 